---
- name: Установка Kibana
  hosts: kibana
  become: yes
  vars:
    elastic_httphost: "{{ hostvars[groups['kibana'][0]]['ansible_host'] }}:9200"
  tasks:

  - name: Установка пакета kibana
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.9-amd64.deb"

  - name: Копируем конфигурационный файл kibana
    template:
      src: kibana.j2
      dest: /etc/kibana/kibana.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name:  Перезапускаем kibana и добавляем в автозагрузку
    service:
      name: kibana
      state: restarted
      enabled: yes